### PR TITLE
Use pluralize for more accuracy and smaller builds

### PR DESCRIPTION
**Pull request by blakeembrey**

### CODE REVIEW

**Comment by dmartinezg** [comment]
If it is more accurate, there should be at least one regression with inflection which went away with singularize.

Please add a regression test for at least one of such cases.

**Comment by blakeembrey** [comment]
@dmartinezg Just added a regression test.

**Comment by dmartinezg** [comment]
Inflection failed on waves?, that's sad. :+1: 

Thanks!

**Comment by blakeembrey** [comment]
Yeah, words ending in `ve` are fun :stuck_out_tongue:

**Comment by dmartinezg** [comment]
:+1:

**Pull request merged**
