### PR TITLE
Added trailing slash support to resourcePathName

### PR DESCRIPTION
**Pull request by gmathieu**

### CODE REVIEW

**Comment by gmathieu** [comment]
Any objections to this PR?

**Comment by dmartinezg** [comment]
Actually, I disagree with this fix, if you use a resource's path that ends in slash, as per defined in the spec, the resourcePathName should be null, right?

I know it does not make sense, but that is the side effect of using slashes at the end or a resource.

**Comment by gmathieu** [comment]
Is there another way to define endpoints trailing slashes and still be able to use the `resourcePathName`?

**Comment by dmartinezg** [comment]
There is no variable for the `parent` of a resource.

**Comment by gmathieu** [comment]
Would you happen to know if `1.0` addresses this?

**Comment by gmathieu** [comment]
I found a way to do this. Sorry for the trouble.

```
# this returned null
/resource/:
    get:
        ...

    /{id}:
        get:
            ...

# this works and seems cleaner
/resource:
    /:
        get:
            ...

    /{id}:
        get:
            ...
```

**Pull request closed without merging**
